f = open('10__19jzu.txt')
s = f.readline()
#s = 'CDaaaaaaaCDddddCD'
"""s = s.replace('CD', '*')
print(s)
s = s.split('*')
print(s)
for i in s:
    if len(i) == 246:
        print('CD'+i+'CD')
a = max([len(i) for i in s])

print(a+4)
"""
if 'CDADADBBCBDEEFEFADAEBBDCCEFEAAAFAFDACCECECFDAFDDACAAABBCCFFBDCCEADBDDAADAECADDEABCEBBECEDDDFADEDDAABEDACBDCABFEBDDCEDDAADDAAABAADACAAEADACEAEDAACAABADBDFEEDEEDBBEADFDADFAEADFDEDCBDDABACBADAAAAACBDFDAABAAABDFCEAADCBAADDAACAEADDFAADAEAFAFDFDAAAADDEDACD' in s:
    print(1)